<?php 
require 'header.php';
require "fonction.php";
?>
<!DOCTYPE html>
<section class="u-clearfix u-container-align-center u-grey-90 current-section u-block-3115-49" custom-posts-hash="[T,T,T]" data-section-properties="{&quot;margin&quot;:&quot;none&quot;,&quot;stretch&quot;:true}" data-id="3115" data-posts-content="[{'images':[],'maps':[],'videos':[],'icons':[],'textWidth':1140,'textHeight':666,'id':1,'groupId':2,'headingProp':'h2','textProp':'text'},{'images':[],'maps':[],'videos':[],'icons':[],'textWidth':1140,'textHeight':666,'id':3,'groupId':2,'headingProp':'h2','textProp':'text'},{'images':[],'maps':[],'videos':[],'icons':[],'textWidth':1140,'textHeight':666,'id':4,'groupId':2,'headingProp':'h2','textProp':'text'}]" data-style="list-control-05" id="carousel_91cf" data-source="fix" data-manual-length-set="true" style="background-image: none; min-height: 2034px">
  
  
  
  
  
  
<div class="u-container-align-center u-container-style u-expanded-width-lg u-expanded-width-xl u-group u-image u-shading u-block-control u-block-3115-88" data-image-width="1980" data-image-height="1320" style="min-height: 501px; background-image: linear-gradient(0deg, rgba(var(--black-r),var(--black-g),var(--black-b),0.15), rgba(var(--black-r),var(--black-g),var(--black-b),0.15)), url(&quot;/1369ae943daeb2/xxxmin.jpg&quot;); height: auto; margin-top: 0; margin-bottom: 0" data-block="14" data-block-type="Group,BackgroundImage">
    <div class="u-container-layout u-valign-top-lg u-valign-top-md u-valign-top-sm u-valign-top-xl u-block-3115-89" style="padding-top: 220px; padding-left: 30px; padding-right: 30px; padding-bottom: 30px" data-container-layout-dom="1"><h1 class="u-align-center u-text u-text-body-alt-color u-text-default u-block-control u-block-3115-57" data-hover-preset-name="zoomIn" data-animation-name="customAnimationIn" data-animation-duration="1500" style="text-shadow: 2px 2px 25px rgba(var(--black-r),var(--black-g),var(--black-b),0.35); background-image: none; font-size: 4.5rem; font-weight: 400; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 0px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3; margin-top: 0; margin-bottom: 0; margin-left: auto; margin-right: auto" data-block="15">Italy Pizza Menu</h1></div>
</div><div class="u-list u-block-control u-block-3115-3" style="grid-template-rows: repeat(3, auto); width: 1140px; margin-top: -78px; margin-left: auto; margin-right: auto; margin-bottom: 0" data-block="16"><div class="u-repeater u-block-control u-block-3115-19" style="grid-template-columns: repeat(3, calc(33.3333% - 13.3333px)); min-height: 1455px; grid-gap: 20px" data-block="17" data-block-type="List">
      <div class="u-container-align-center u-container-style u-list-item u-repeater-item u-shape-rectangle u-white u-block-control u-block-3115-4" data-hover-preset-name="fadeIn" data-animation-name="customAnimationIn" data-animation-duration="1500" style="background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1" data-block="18">
        <div class="u-container-layout u-similar-container u-valign-top u-block-3115-5" style="padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px" data-container-layout-dom="2">
          <img class="u-expanded-width u-image u-image-default u-block-control u-block-3115-50" src="/5ed991aa4caa6/45.jpg" alt="" data-image-width="700" data-image-height="560" data-hover-preset-name="zoomIn" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3" data-block="19"><h4 class="u-align-center u-custom-font u-text u-block-control u-block-3115-10" style="font-family: &quot;Palanquin Dark&quot;; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="20">​Cheese Pizza</h4>
          <p class="u-align-center u-text u-block-control u-block-3115-13" style="font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="21">​Get our Manhattan Classic Cheese Pizza with your choice of sauce and crust. </p>
          
        <p class="u-align-center u-text u-text-palette-2-base u-block-control u-block-3115-90" data-hover-preset-name="spiral" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3" data-block="22">​$15.95</p></div>
      </div>
      <div class="u-container-align-center u-container-style u-list-item u-repeater-item u-shape-rectangle u-video-cover u-white u-block-control u-block-3115-6" data-hover-preset-name="fadeIn" data-animation-name="customAnimationIn" data-animation-duration="1500" style="background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1" data-block="23" data-block-type="ListItem">
        <div class="u-container-layout u-similar-container u-valign-top u-block-3115-7" style="padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px" data-container-layout-dom="3">
          <img class="u-expanded-width u-image u-image-default u-block-control u-block-3115-51" src="/5331596c9092f/7777.jpg" alt="" data-image-width="700" data-image-height="560" data-hover-preset-name="zoomIn" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3" data-block="24" data-block-type="Image"><h4 class="u-align-center u-custom-font u-text u-block-control u-block-3115-11" style="font-family: &quot;Palanquin Dark&quot;; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="25" data-block-type="Text">​Pepperoni Pizza</h4>
          <p class="u-align-center u-text u-block-control u-block-3115-14" style="font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="26">​Get our classic Pepperoni pizza with your choice of sauce and crust.<br></p>
          
        <p class="u-align-center u-text u-text-palette-2-base u-block-control u-block-3115-91" data-hover-preset-name="spiral" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3" data-block="27">​$16.35</p></div>
      </div>
      <div class="u-container-align-center u-container-style u-list-item u-repeater-item u-shape-rectangle u-video-cover u-white u-block-control u-block-3115-8" data-hover-preset-name="fadeIn" data-animation-name="customAnimationIn" data-animation-duration="1500" style="background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1" data-block="28" data-block-type="ListItem">
        <div class="u-container-layout u-similar-container u-valign-top u-block-3115-9" style="padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px" data-container-layout-dom="4">
          <img class="u-expanded-width u-image u-image-default u-block-control u-block-3115-52" src="/122520d48b6c4b/p1.jpg" alt="" data-image-width="700" data-image-height="560" data-hover-preset-name="zoomIn" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3" data-block="29"><h4 class="u-align-center u-custom-font u-text u-block-control u-block-3115-12" style="font-family: &quot;Palanquin Dark&quot;; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="30" data-block-type="Text">Vegetarian Pizza</h4>
          <p class="u-align-center u-text u-block-control u-block-3115-15" style="font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="31">​Tomato Sauce, Mozzarella, Green Pepper, Onions, Fresh Mushrooms, Tomatoes, and Black Olives.</p>
          
        <p class="u-align-center u-text u-text-palette-2-base u-block-control u-block-3115-92" data-hover-preset-name="spiral" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3" data-block="32">​$19.95</p></div>
      </div>
    <div class="u-container-align-center u-container-style u-list-item u-repeater-item u-shape-rectangle u-video-cover u-white u-block-control u-block-3115-58" data-hover-preset-name="fadeIn" data-animation-name="customAnimationIn" data-animation-duration="1500" style="background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1" data-block="33" data-block-type="ListItem">
        <div class="u-container-layout u-similar-container u-valign-top u-block-3115-59" style="padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px" data-container-layout-dom="5">
          <img class="u-expanded-width u-image u-image-default u-block-control u-block-3115-60" src="/1315a8775f376a/09.jpg" alt="" data-image-width="996" data-image-height="881" data-hover-preset-name="zoomIn" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3" data-block="34" data-block-type="Image"><h4 class="u-align-center u-custom-font u-text u-block-control u-block-3115-61" style="font-family: &quot;Palanquin Dark&quot;; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="35">​Mozzarella Pizza</h4>
          <p class="u-align-center u-text u-block-control u-block-3115-62" style="font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="36">​Secret homemade spicy sauce, with curly cuts pepperoni and fresh mozzarella</p>
          
        <p class="u-align-center u-text u-text-palette-2-base u-block-control u-block-3115-93" data-hover-preset-name="spiral" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3" data-block="37">​$22.55</p></div>
      </div><div class="u-container-align-center u-container-style u-list-item u-repeater-item u-shape-rectangle u-video-cover u-white u-block-control u-block-3115-63" data-hover-preset-name="fadeIn" data-animation-name="customAnimationIn" data-animation-duration="1500" style="background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1" data-block="38" data-block-type="ListItem">
        <div class="u-container-layout u-similar-container u-valign-top u-block-3115-64" style="padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px" data-container-layout-dom="6">
          <img class="u-expanded-width u-image u-image-default u-block-control u-block-3115-65" src="/6cc8733fcf79f/46.jpg" alt="" data-image-width="996" data-image-height="881" data-hover-preset-name="zoomIn" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3" data-block="39" data-block-type="Image"><h4 class="u-align-center u-custom-font u-text u-block-control u-block-3115-66" style="font-family: &quot;Palanquin Dark&quot;; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="40">​Sicilian Pizza</h4>
          <p class="u-align-center u-text u-block-control u-block-3115-67" style="font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="41">​Salami, pepperoni, Italian&nbsp;sausage, green peppers &amp; onions</p>
          
        <p class="u-align-center u-text u-text-palette-2-base u-block-control u-block-3115-94" data-hover-preset-name="spiral" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3" data-block="42">​$19.15</p></div>
      </div><div class="u-container-align-center u-container-style u-list-item u-repeater-item u-shape-rectangle u-video-cover u-white u-block-control u-block-3115-68" data-hover-preset-name="fadeIn" data-animation-name="customAnimationIn" data-animation-duration="1500" style="background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1" data-block="43" data-block-type="ListItem">
        <div class="u-container-layout u-similar-container u-valign-top u-block-3115-69" style="padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px" data-container-layout-dom="7">
          <img class="u-expanded-width u-image u-image-default u-block-control u-block-3115-70" src="/6d686964f2328/68.jpg" alt="" data-image-width="996" data-image-height="881" data-hover-preset-name="zoomIn" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3" data-block="44" data-block-type="Image"><h4 class="u-align-center u-custom-font u-text u-block-control u-block-3115-71" style="font-family: &quot;Palanquin Dark&quot;; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="45">Grilled Pizza</h4>
          <p class="u-align-center u-text u-block-control u-block-3115-72" style="font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="46">​Tomato, onions, green peppers&nbsp;&amp; grilled or fried chicken</p>
          
        <p class="u-align-center u-text u-text-palette-2-base u-block-control u-block-3115-95" data-hover-preset-name="spiral" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3" data-block="47">​$14.25</p></div>
      </div><div class="u-container-align-center u-container-style u-list-item u-repeater-item u-shape-rectangle u-video-cover u-white u-block-control u-block-3115-73" data-hover-preset-name="fadeIn" data-animation-name="customAnimationIn" data-animation-duration="1500" style="background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1" data-block="48">
        <div class="u-container-layout u-similar-container u-valign-top u-block-3115-74" style="padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px" data-container-layout-dom="8">
          <img class="u-expanded-width u-image u-image-default u-block-control u-block-3115-75" src="/1b09bb62b9c3c9/53.jpg" alt="" data-image-width="996" data-image-height="881" data-hover-preset-name="zoomIn" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3" data-block="49"><h4 class="u-align-center u-custom-font u-text u-block-control u-block-3115-76" style="font-family: &quot;Palanquin Dark&quot;; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="50">Veggie Pizza</h4>
          <p class="u-align-center u-text u-block-control u-block-3115-77" style="font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="51">​Black olives, green pepper, onion,&nbsp;mushroom &amp; tomato</p>
          
        <p class="u-align-center u-text u-text-palette-2-base u-block-control u-block-3115-96" data-hover-preset-name="spiral" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3" data-block="52">​$12.45</p></div>
      </div><div class="u-container-align-center u-container-style u-list-item u-repeater-item u-shape-rectangle u-video-cover u-white u-block-control u-block-3115-78" data-hover-preset-name="fadeIn" data-animation-name="customAnimationIn" data-animation-duration="1500" style="background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1" data-block="53" data-block-type="ListItem">
        <div class="u-container-layout u-similar-container u-valign-top u-block-3115-79" style="padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px" data-container-layout-dom="9">
          <img class="u-expanded-width u-image u-image-default u-block-control u-block-3115-80" src="/47e6d43e62a64/22.jpg" alt="" data-image-width="996" data-image-height="881" data-hover-preset-name="zoomIn" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3" data-block="54" data-block-type="Image"><h4 class="u-align-center u-custom-font u-text u-block-control u-block-3115-81" style="font-family: &quot;Palanquin Dark&quot;; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="55">Chicken Pizza</h4>
          <p class="u-align-center u-text u-block-control u-block-3115-82" style="font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="56">​Alfredo sauce, grilled chicken,
<br>mushrooms &amp; black olives</p>
          
        <p class="u-align-center u-text u-text-palette-2-base u-block-control u-block-3115-97" data-hover-preset-name="spiral" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3" data-block="57">​$13.55</p></div>
      </div><div class="u-container-align-center u-container-style u-list-item u-repeater-item u-shape-rectangle u-video-cover u-white u-block-control u-block-3115-83" data-hover-preset-name="fadeIn" data-animation-name="customAnimationIn" data-animation-duration="1500" style="background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1" data-block="58">
        <div class="u-container-layout u-similar-container u-valign-top u-block-3115-84" style="padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px" data-container-layout-dom="10">
          <img class="u-expanded-width u-image u-image-default u-block-control u-block-3115-85" src="/5736e70545c1a/43.jpg" alt="" data-image-width="996" data-image-height="881" data-hover-preset-name="zoomIn" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3" data-block="59"><h4 class="u-align-center u-custom-font u-text u-block-control u-block-3115-86" style="font-family: &quot;Palanquin Dark&quot;; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="60">Hot Brown Pizza</h4>
          <p class="u-align-center u-text u-block-control u-block-3115-87" style="font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0" data-block="61">​Roasted turkey, bacon, tomato over
<br>creamy cheddar alfredo sauce</p>
          
        <p class="u-align-center u-text u-text-palette-2-base u-block-control u-block-3115-98" data-hover-preset-name="spiral" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="500" style="margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3" data-block="62">​$18.00</p></div>
      </div></div></div><p class="u-align-center u-text u-block-control u-block-3115-22" data-hover-preset-name="zoomIn" data-animation-name="customAnimationIn" data-animation-duration="1500" data-animation-delay="750" style="width: 446px; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3; margin-top: 41px; margin-left: auto; margin-right: auto; margin-bottom: 60px" data-block="63">Images from <a href="https://www.freepik.com" class="u-active-none u-border-1 u-border-active-palette-2-base u-border-hover-palette-2-base u-border-no-left u-border-no-right u-border-no-top u-border-white u-bottom-left-radius-0 u-bottom-right-radius-0 u-btn u-button-link u-button-style u-hover-none u-none u-radius-0 u-text-body-alt-color u-top-left-radius-0 u-top-right-radius-0 u-block-control u-block-3115-23" target="_blank" style="background-image: none; padding-top: 0; padding-bottom: 0; padding-left: 0; padding-right: 0" data-block="64">Freepik</a></p><style data-mode="XL" data-visited="true">@media (max-width: 0px) { .u-block-3115-49 {background-image: none; min-height: 2034px}
.u-block-3115-88 {min-height: 501px; background-image: linear-gradient(0deg, rgba(var(--black-r),var(--black-g),var(--black-b),0.15), rgba(var(--black-r),var(--black-g),var(--black-b),0.15)), url("/1369ae943daeb2/xxxmin.jpg"); height: auto; margin-top: 0; margin-bottom: 0}
.u-block-3115-89 {padding-top: 220px; padding-left: 30px; padding-right: 30px; padding-bottom: 30px}
.u-block-3115-57 {text-shadow: 2px 2px 25px rgba(var(--black-r),var(--black-g),var(--black-b),0.35); background-image: none; font-size: 4.5rem; font-weight: 400; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 0px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3; margin-top: 0; margin-bottom: 0; margin-left: auto; margin-right: auto}
.u-block-3115-3 {grid-template-rows: repeat(3, auto); width: 1140px; margin-top: -78px; margin-left: auto; margin-right: auto; margin-bottom: 0}
.u-block-3115-19 {grid-template-columns: repeat(3, calc(33.3333% - 13.3333px)); min-height: 1455px; grid-gap: 20px}
.u-block-3115-4 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-5 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-50 {height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-10 {font-family: "Palanquin Dark"; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-13 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-90 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-6 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-7 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-51 {height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-11 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-14 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-91 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-8 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-9 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-52 {height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-12 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-15 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-92 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-58 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-59 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-60 {height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-61 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-62 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-93 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-63 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-64 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-65 {height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-66 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-67 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-94 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-68 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-69 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-70 {height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-71 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-72 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-95 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-73 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-74 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-75 {height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-76 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-77 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-96 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-78 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-79 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-80 {height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-81 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-82 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-97 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-83 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-84 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-85 {height: 258px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-86 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-87 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-98 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-22 {width: 446px; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3; margin-top: 41px; margin-left: auto; margin-right: auto; margin-bottom: 60px}
.u-block-3115-23 {background-image: none; padding-top: 0; padding-bottom: 0; padding-left: 0; padding-right: 0} }</style><style data-mode="LG">@media (max-width: 0px) { .u-block-3115-49 {background-image: none; min-height: 2034px}
.u-block-3115-88 {background-image: linear-gradient(0deg, rgba(var(--black-r),var(--black-g),var(--black-b),0.15), rgba(var(--black-r),var(--black-g),var(--black-b),0.15)), url("/1369ae943daeb2/xxxmin.jpg"); min-height: 501px; margin-top: 0; margin-bottom: 0}
.u-block-3115-89 {padding-top: 220px; padding-left: 30px; padding-right: 30px; padding-bottom: 30px}
.u-block-3115-57 {text-shadow: 2px 2px 25px rgba(var(--black-r),var(--black-g),var(--black-b),0.35); background-image: none; font-size: 4.5rem; font-weight: 400; margin-top: 0; margin-bottom: 0; margin-left: auto; margin-right: auto; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 0px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-3 {grid-template-rows: repeat(3, auto); width: 940px; margin-top: -78px; margin-left: auto; margin-right: auto; margin-bottom: 0}
.u-block-3115-19 {grid-template-columns: repeat(3, calc(33.333333333333336% - 13.3333px)); min-height: 1198px; grid-gap: 20px}
.u-block-3115-4 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-5 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-50 {height: 204px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-10 {font-family: "Palanquin Dark"; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-13 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-90 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-6 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-7 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-51 {height: 204px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-11 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-14 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-91 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-8 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-9 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-52 {height: 204px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-12 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-15 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-92 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-58 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-59 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-60 {height: 204px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-61 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-62 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-93 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-63 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-64 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-65 {height: 204px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-66 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-67 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-94 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-68 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-69 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-70 {height: 204px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-71 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-72 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-95 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-73 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-74 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-75 {height: 204px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-76 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-77 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-96 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-78 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-79 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-80 {height: 204px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-81 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-82 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-97 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-83 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-84 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-85 {height: 204px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-86 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-87 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-98 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-22 {width: 446px; margin-top: 41px; margin-left: auto; margin-right: auto; margin-bottom: 60px; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-23 {background-image: none; padding-top: 0; padding-bottom: 0; padding-left: 0; padding-right: 0} }</style><style data-mode="MD" data-visited="true">@media (max-width: 0px) { .u-block-3115-49 {background-image: none; min-height: 2885px}
.u-block-3115-88 {background-image: linear-gradient(0deg, rgba(var(--black-r),var(--black-g),var(--black-b),0.15), rgba(var(--black-r),var(--black-g),var(--black-b),0.15)), url("/1369ae943daeb2/xxxmin.jpg"); min-height: 501px; margin-top: 0; margin-bottom: 0}
.u-block-3115-89 {padding-top: 195px; padding-left: 30px; padding-right: 30px; padding-bottom: 30px}
.u-block-3115-57 {text-shadow: 2px 2px 25px rgba(var(--black-r),var(--black-g),var(--black-b),0.35); background-image: none; font-size: 4.5rem; font-weight: 400; margin-top: 0; margin-bottom: 0; margin-left: auto; margin-right: auto; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 0px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-3 {grid-template-rows: repeat(3, auto); width: 720px; margin-top: -78px; margin-left: auto; margin-right: auto; margin-bottom: 0}
.u-block-3115-19 {grid-template-columns: repeat(2, calc(50% - 9.999975px)); min-height: 2332px; grid-gap: 20px}
.u-block-3115-4 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-5 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-50 {height: 242px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-10 {font-family: "Palanquin Dark"; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-13 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-90 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-6 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-7 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-51 {height: 242px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-11 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-14 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-91 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-8 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-9 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-52 {height: 242px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-12 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-15 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-92 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-58 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-59 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-60 {height: 242px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-61 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-62 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-93 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-63 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-64 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-65 {height: 242px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-66 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-67 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-94 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-68 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-69 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-70 {height: 242px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-71 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-72 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-95 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-73 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-74 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-75 {height: 242px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-76 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-77 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-96 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-78 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-79 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-80 {height: 242px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-81 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-82 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-97 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-83 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-84 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-85 {height: 242px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-86 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-87 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-98 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-22 {width: 446px; margin-top: 41px; margin-left: auto; margin-right: auto; margin-bottom: 60px; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-23 {background-image: none; padding-top: 0; padding-bottom: 0; padding-left: 0; padding-right: 0} }</style><style data-mode="SM" data-visited="true">@media (max-width: 0px) { .u-block-3115-49 {background-image: none; min-height: 6075px}
.u-block-3115-88 {background-image: linear-gradient(0deg, rgba(var(--black-r),var(--black-g),var(--black-b),0.15), rgba(var(--black-r),var(--black-g),var(--black-b),0.15)), url("/1369ae943daeb2/xxxmin.jpg"); min-height: 501px; margin-top: 0; margin-bottom: 0}
.u-block-3115-89 {padding-top: 255px; padding-left: 10px; padding-right: 10px; padding-bottom: 30px}
.u-block-3115-57 {text-shadow: 2px 2px 25px rgba(var(--black-r),var(--black-g),var(--black-b),0.35); background-image: none; font-size: 4.5rem; font-weight: 400; margin-top: 0; margin-bottom: 0; margin-left: auto; margin-right: auto; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 0px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-3 {grid-template-rows: repeat(3, auto); width: 540px; margin-top: -78px; margin-left: auto; margin-right: auto; margin-bottom: 0}
.u-block-3115-19 {grid-template-columns: 100%; min-height: 2332px; grid-gap: 20px}
.u-block-3115-4 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-5 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-50 {height: 419px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-10 {font-family: "Palanquin Dark"; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-13 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-90 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-6 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-7 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-51 {height: 419px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-11 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-14 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-91 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-8 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-9 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-52 {height: 419px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-12 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-15 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-92 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-58 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-59 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-60 {height: 419px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-61 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-62 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-93 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-63 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-64 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-65 {height: 419px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-66 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-67 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-94 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-68 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-69 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-70 {height: 419px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-71 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-72 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-95 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-73 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-74 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-75 {height: 419px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-76 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-77 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-96 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-78 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-79 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-80 {height: 419px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-81 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-82 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-97 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-83 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-84 {padding-top: 30px; padding-bottom: 30px; padding-left: 30px; padding-right: 30px}
.u-block-3115-85 {height: 419px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-86 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-87 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-98 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-22 {width: 446px; margin-top: 41px; margin-left: auto; margin-right: auto; margin-bottom: 60px; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-23 {background-image: none; padding-top: 0; padding-bottom: 0; padding-left: 0; padding-right: 0} }</style><style data-mode="XS" data-visited="true">@media (max-width: 0px) { .u-block-3115-49 {background-image: none; min-height: 4983px}
.u-block-3115-88 {background-image: linear-gradient(0deg, rgba(var(--black-r),var(--black-g),var(--black-b),0.15), rgba(var(--black-r),var(--black-g),var(--black-b),0.15)), url("/1369ae943daeb2/xxxmin.jpg"); min-height: 501px; margin-top: 0; margin-bottom: 0}
.u-block-3115-89 {padding-top: 155px; padding-left: 10px; padding-right: 10px; padding-bottom: 30px}
.u-block-3115-57 {text-shadow: 2px 2px 25px rgba(var(--black-r),var(--black-g),var(--black-b),0.35); background-image: none; font-weight: 400; width: auto; margin-top: 122px; margin-left: 38px; margin-right: 38px; margin-bottom: 0; font-size: 3rem; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 0px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-3 {grid-template-rows: repeat(3, auto); width: 340px; margin-top: -78px; margin-left: auto; margin-right: auto; margin-bottom: 0}
.u-block-3115-19 {grid-template-columns: 100%; min-height: 2332px; grid-gap: 20px}
.u-block-3115-4 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-5 {padding-top: 30px; padding-bottom: 30px; padding-left: 20px; padding-right: 20px}
.u-block-3115-50 {height: 279px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-10 {font-family: "Palanquin Dark"; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-13 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-90 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-6 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-7 {padding-top: 30px; padding-bottom: 30px; padding-left: 20px; padding-right: 20px}
.u-block-3115-51 {height: 279px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-11 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-14 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-91 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-8 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-9 {padding-top: 30px; padding-bottom: 30px; padding-left: 20px; padding-right: 20px}
.u-block-3115-52 {height: 279px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-12 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-15 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-92 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-58 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-59 {padding-top: 30px; padding-bottom: 30px; padding-left: 20px; padding-right: 20px}
.u-block-3115-60 {height: 279px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-61 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-62 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-93 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-63 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-64 {padding-top: 30px; padding-bottom: 30px; padding-left: 20px; padding-right: 20px}
.u-block-3115-65 {height: 279px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-66 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-67 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-94 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-68 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-69 {padding-top: 30px; padding-bottom: 30px; padding-left: 20px; padding-right: 20px}
.u-block-3115-70 {height: 279px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-71 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-72 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-95 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-73 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-74 {padding-top: 30px; padding-bottom: 30px; padding-left: 20px; padding-right: 20px}
.u-block-3115-75 {height: 279px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-76 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-77 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-96 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-78 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-79 {padding-top: 30px; padding-bottom: 30px; padding-left: 20px; padding-right: 20px}
.u-block-3115-80 {height: 279px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-81 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-82 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-97 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-83 {background-image: none; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 1}
.u-block-3115-84 {padding-top: 30px; padding-bottom: 30px; padding-left: 20px; padding-right: 20px}
.u-block-3115-85 {height: 279px; margin-top: 0; margin-bottom: 0; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 100px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-86 {font-family: "Palanquin Dark"; font-weight: 400; text-transform: none; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-87 {font-style: italic; margin-top: 20px; margin-left: 0; margin-right: 0; margin-bottom: 0}
.u-block-3115-98 {margin-left: 0; margin-right: 0; margin-bottom: 0; font-weight: 700; --animation-custom_in-translate_x: 50px; --animation-custom_in-rotate: 180deg; --animation-custom_in-scale: 0.3}
.u-block-3115-22 {width: 340px; margin-top: 41px; margin-left: auto; margin-right: auto; margin-bottom: -1032px; --animation-custom_in-translate_x: 0px; --animation-custom_in-translate_y: 300px; --animation-custom_in-opacity: 0; --animation-custom_in-rotate: 0deg; --animation-custom_in-scale: 0.3}
.u-block-3115-23 {background-image: none; padding-top: 0; padding-bottom: 0; padding-left: 0; padding-right: 0} }</style></section>
</html>
